config/routes.rb
Rails.application.routes.draw do
  resources :to_do_features
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "sessions#new"
  get "users-view", to: "users#index"
  # get "login", to: "login#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :to_dos do
    resources :to_do_features
  end
  delete "logout", to: "sessions#destroy"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  has_many :to_do_features, dependent: :destroy
end

app/models/to_do_feature.rb
class ToDoFeature < ApplicationRecord
  belongs_to :to_do
end

app/models/user.rb
class User < ApplicationRecord
  has_rich_text :description
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  helper_method :current_user, :authenticated?
  around_action :switch_locale
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def authenticated?
    current_user.present?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #render login form
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to to_dos_path, notice: "Logged in Successfully!!"
    else
      flash.now[:alert] = "Invalid out successfully!"
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Loggout Successfully!"
  end
end

app/controllers/to_do_features_controller.rb
class ToDoFeaturesController < ApplicationController
  before_action :set_to_do_feature, only: %i[ show edit update destroy ]

  # GET /to_do_features or /to_do_features.json
  def index
    if params[:to_do_id]
      @to_do = ToDo.find(params[:to_do_id])
      @to_do_features = @to_do.to_do_features
    else
      @to_do_features = ToDoFeature.all
    end
  end

  # GET /to_do_features/1 or /to_do_features/1.json
  def show
  end

  # GET /to_do_features/new
  def new
    @to_do_feature = ToDoFeature.new
  end

  # GET /to_do_features/1/edit
  def edit
  end

  # POST /to_do_features or /to_do_features.json
  def create
    @to_do_feature = ToDoFeature.new(to_do_feature_params)
    @to_do_feature.status = 0
    @to_do_feature.to_do_id = @to_do.id

    respond_to do |format|
      if @to_do_feature.save
        format.html { redirect_to @to_do_features, notice: "To do feature was successfully created." }
        format.json { render :show, status: :created, location: @to_do_feature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @to_do_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_features/1 or /to_do_features/1.json
  def update
    respond_to do |format|
      if @to_do_feature.update(to_do_feature_params)
        format.html { redirect_to @to_do_feature, notice: "To do feature was successfully updated." }
        format.json { render :show, status: :ok, location: @to_do_feature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @to_do_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_features/1 or /to_do_features/1.json
  def destroy
    @to_do_feature.destroy!

    respond_to do |format|
      format.html { redirect_to to_do_features_path, status: :see_other, notice: "To do feature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_feature
      @to_do_feature = ToDoFeature.find(params.expect(:id))
    end
  def set_to_do
    @to_do = Todo.find(params.expect(:id))
  end
    # Only allow a list of trusted parameters through.
    def to_do_feature_params
      params.expect(to_do_feature: [ :name, :description ])
    end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  def index
    id = session[:user_id]
    @to_dos = ToDo.where(userId: id)
  end
  def new
    @to_do = ToDo.new
  end

  def create
    @to_do = ToDo.new(to_do_params)
    @to_do.userId = current_user.id
    @to_do.status = 0
    if @to_do.save
      redirect_to to_dos_path, notice:"ToDo created Successfully!!"
    else
      render :new
    end
  end

  private
  def to_do_params
    params.require(:to_do).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render "new" , status: :unprocessable_entity
      end
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/to_do_features_helper.rb
module ToDoFeaturesHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
    <% if authenticated? %>
      <span>Welcome, <%= current_user.email %>!</span>
      <%= button_to "Logout",logout_path, method: :delete %>
    <% end %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/to_do_features/_form.html.erb
<%= form_with(model: to_do_feature) do |form| %>
  <% if to_do_feature.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(to_do_feature.errors.count, "error") %> prohibited this to_do_feature from being saved:</h2>

      <ul>
        <% to_do_feature.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :todoId, style: "display: block" %>
    <%= form.number_field :todoId %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/to_do_features/_to_do_feature.html.erb
<div id="<%= dom_id to_do_feature %>">
  <p>
    <strong>Name:</strong>
    <%= to_do_feature.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= to_do_feature.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= to_do_feature.status %>
  </p>

  <p>
    <strong>Todoid:</strong>
    <%= to_do_feature.to_do_id %>
  </p>
</div>

app/views/to_do_features/edit.html.erb
<% content_for :title, "Editing to do feature" %>

<h1>Editing to do feature</h1>

<%= render "form", to_do_feature: @to_do_feature %>

<br>

<div>
  <%= link_to "Show this to do feature", @to_do_feature %> |
  <%= link_to "Back to to do features", to_do_features_path %>
</div>

app/views/to_do_features/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "To do features" %>

<% if @todo %>
  <h1>Welcome to, <%= @to_do.name %></h1>
  <% else %>
  <h1>All Todo Feature</h1>
<% end %>

<%= link_to "Back your task", to_dos_path %>
<div id="to_do_features">
  <% @to_do_features.each do |to_do_feature| %>
    <%= render to_do_feature %>
    <p>
      <%= link_to "Show this to do feature", to_do_feature %>
    </p>
  <% end %>
</div>

<%= link_to "New to do feature", new_to_do_feature_path %>

app/views/to_do_features/new.html.erb
<% content_for :title, "New to do feature" %>

<h1>New to do feature</h1>

<%= form_with model: @to_do_feature do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Back to to do features", to_do_features_path %>
</div>

app/views/to_do_features/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @to_do_feature %>

<div>
  <%= link_to "Edit this to do feature", edit_to_do_feature_path(@to_do_feature) %> |
  <%= link_to "Back to to do features", to_do_features_path %>

  <%= button_to "Destroy this to do feature", @to_do_feature, method: :delete %>
</div>

app/views/to_dos/index.html.erb
<h1>ToDoList</h1>
<%= link_to "New Work", new_to_do_path %>
<% if @to_dos.present? && @to_dos.any? %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">Id</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">CreatedAt</th>
    <th scope="col">UpdatedAt</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
    <tr>
  <%
  @to_dos.each do |todo|
  %>
      <td><%=todo.id%></td>
      <td><%= todo.name %></td>
      <td><%= todo.description %></td>
      <td><%= todo.created_at%></td>
      <td><%= todo.updated_at%></td>
      <td>
        <%= link_to  "Edit"%>
        <%= button_to "Delete", data: {turbo_confirm: "Are you sure?"}%>
        <%= button_to "View Detail Task", to_do_to_do_features_path(todo), method: :get%>
      </td>
    </tr>
  <%end%>
  <% else %>
  <p>You haven't any records</p>
  </tbody>
  <%#= link_to "Home", root_path %>
</table>
<% end %>

app/views/to_dos/new.html.erb
<h1>New Task</h1>
<%= form_with model: @to_do do |form| %>
  <div>
    <span>Name of task:</span>
    <%= form.text_field :name %></div></n>
    <span>Description of task:</span>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.submit %>
    <%= link_to "Back", to_dos_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1> Update User</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.text_field :email %>
    <%= form.text_field :password %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>User List</h1>
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Id</th>
    <th scope="col">Email</th>
    <th scope="col">Password</th>
    <th scope="col">CreatedAt</th>
    <th scope="col">UpdatedAt</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <%
    @users.each do |user|
  %>
  <tr>
    <th scope="row">1</th>
    <td><%= user.id %></td>
    <td><%=user.email %></td>
    <td><%=user.password%></td>
    <td><%=user.created_at%></td>
    <td><%=user.updated_at%></td>
    <td>
      <%= link_to  "Edit",edit_user_path(user)%>
      <%= button_to "Delete", user, method: :delete, data: {turbo_confirm: "Are you sure?"}%>
    </td>
  </tr>
  <% end %>
  </tbody>
  <%= link_to "New User", new_user_path %>
  <%= link_to "Home", root_path %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.text_field :email %>
    <%= form.text_field :password %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>